### ISSUE TITLE
Update for sensor.x fails

### ISSUE THREAD

**Issue by BigNocciolino** [BigNocciolino/CryptoTracker#19]
Since the `req` object (that contain the request object) it's initialized as a string, sometimes when the sensor refuses to update, the `req` object remains a string.

**Full log trace:**

```

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 512, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 716, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/cryptostate/sensor.py", line 146, in _update
    data = get_data(self._compare)
  File "/config/custom_components/cryptostate/sensor.py", line 61, in get_data
    if (req.status_code == 200):
AttributeError: 'str' object has no attribute 'status_code
```

**Comment by smarthomejunkie** [comment]
+1

**Comment by kevincaradant** [comment]
+1 , HA don't start anymore because of this issue :(

![image](https://user-images.githubusercontent.com/6093175/152647971-fe038a78-af1f-4e42-a440-d64b389de8a4.png)

Edit: Finally, it started 10 minutes later. (I don't know if it's the only reason of this delay).
But I think it wait the request timeout of each crypto that it try to load  If you have like me 10 or 15 crypto, it's pretty long to start :D

**Comment by BigNocciolino** [comment]
Hi I'm closing all the old issues, if there are problems with the new version, please open a new issue
